# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: thalesesecurity/contribstats
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
storage:
  size: 200Gi

config:
  interval: 60
  token: ""
  organizations:
  - unorepo
  domains:
  - thalesesecurity.com
  - thalesesec.net
  - thales-e-security.com
  - thales-esecurity.com
  cache: /storage

ingress:
  enabled: false
  istio: false
  annotations: {
  }
  # kubernetes.io/tls-acme: "true"
  path: /.*
  hosts:
  - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
