version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    working_directory: ~/github.com/thales-e-security/contribstats
    steps:
    - checkout
    - run: go mod download
    - run: go test -v $(go list ./... | grep -v /vendor/)
    - run: go test -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /vendor/)
    - run: bash <(curl -s https://codecov.io/bash)
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker build and push
        command: |
          docker build -t thalesesecurity/contribstats:latest .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push thalesesecurity/contribstats:latest